# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_add_star.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogAddStar(object):
    def setupUi(self, DialogAddStar):
        DialogAddStar.setObjectName("DialogAddStar")
        DialogAddStar.resize(300, 190)
        self.gridLayout_2 = QtWidgets.QGridLayout(DialogAddStar)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(17, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(DialogAddStar)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_name = QtWidgets.QLineEdit(DialogAddStar)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.gridLayout.addWidget(self.lineEdit_name, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(DialogAddStar)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_x = QtWidgets.QLineEdit(DialogAddStar)
        self.lineEdit_x.setObjectName("lineEdit_x")
        self.gridLayout.addWidget(self.lineEdit_x, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(DialogAddStar)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_y = QtWidgets.QLineEdit(DialogAddStar)
        self.lineEdit_y.setObjectName("lineEdit_y")
        self.gridLayout.addWidget(self.lineEdit_y, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(DialogAddStar)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit_hour_angle = QtWidgets.QLineEdit(DialogAddStar)
        self.lineEdit_hour_angle.setObjectName("lineEdit_hour_angle")
        self.gridLayout.addWidget(self.lineEdit_hour_angle, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(DialogAddStar)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.lineEdit_declination = QtWidgets.QLineEdit(DialogAddStar)
        self.lineEdit_declination.setObjectName("lineEdit_declination")
        self.gridLayout.addWidget(self.lineEdit_declination, 4, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(17, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogAddStar)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 3, 0, 1, 1)

        self.retranslateUi(DialogAddStar)
        self.buttonBox.accepted.connect(DialogAddStar.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogAddStar.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogAddStar)

    def retranslateUi(self, DialogAddStar):
        _translate = QtCore.QCoreApplication.translate
        DialogAddStar.setWindowTitle(_translate("DialogAddStar", "添加星星"))
        self.label.setText(_translate("DialogAddStar", "名字"))
        self.label_2.setText(_translate("DialogAddStar", "x"))
        self.label_3.setText(_translate("DialogAddStar", "y"))
        self.label_4.setText(_translate("DialogAddStar", "时角"))
        self.lineEdit_hour_angle.setPlaceholderText(_translate("DialogAddStar", "--h--m--s"))
        self.label_5.setText(_translate("DialogAddStar", "赤纬"))
        self.lineEdit_declination.setPlaceholderText(_translate("DialogAddStar", "--°--\'--\""))
